apache/incubator-wayang

.travis.yml
pom.xml
wayang-api/wayang-api-python/pom.xml
wayang-api/wayang-api-scala-java/pom.xml
wayang-platforms/wayang-spark/pom.xml
wayang-plugins/wayang-iejoin/pom.xml
wayang-profiler/pom.xml
wayang-tests-integration/pom.xml

During the compilation in the profile scala-11, it was not compiling the code because the version of Apache Spark was not compatible. It created a change of version depending on the profile. In the case of profile scala-11 the Apache Spark will be 2.4.8. However,  in other profiles like scala-12 the Apache Spark version will 3.X

[WAYANG-40] Update version of spark depending on the profile

---

wayang-benchmark/src/main/scala/org/apache/wayang/apps/simwords/SelectNearestCentroidFunction.scala

As discussed on the mailing list, this resolves an issue where IntelliJ cannot build the project due to a faulty maven import. I'm thinking that it might be something like the following IntelliJ bug, because we are importing Spark in a tricky way (different versions based on different profiles):
https://youtrack.jetbrains.com/issue/IDEA-98503
This was the only place in the code where `org.slf4j.LoggerFactory` was used.

Change SelectNearestCentroidFunction to use org.apache.logging.log4j.LogManager instead of org.slf4j.LoggerFactory

---

wayang-commons/wayang-utils-profile-db/src/main/java/org/apache/wayang/commons/util/profiledb/instrumentation/StopWatch.java

Code, which does not come from an direct apache wayang comitter can't be re-licensed, instead the inclusion has to be noted in NOTICE. A good practise is to add the short notice into the files why the standard header is missing.

removed wrong placed license

---

pom.xml

tested 0.6.0 release, and given old versions of plugins, it's as expected not reproducible...
see https://maven.apache.org/guides/mini/guide-reproducible-builds.html#faq

upgrade plugins for Reproducible Builds

---

wayang-commons/pom.xml
wayang-tests-integration/pom.xml

delete paranamer-2.3 from dependecies to just work with paranamer 2.8, because exception at runtime in spark and other platforms

[BUG] delete paranamer-2.3 from dependecies

---

pom.xml
wayang-commons/pom.xml
wayang-docs/src/main/resources/Gemfile.lock
wayang-platforms/wayang-postgres/pom.xml
wayang-platforms/wayang-spark/pom.xml

Bump postgresql in /wayang-platforms/wayang-postgres (#4)
Bumps [postgresql](https://github.com/pgjdbc/pgjdbc) from 9.4.1208 to 42.3.3.
- [Release notes](https://github.com/pgjdbc/pgjdbc/releases)
- [Changelog](https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md)
- [Commits](https://github.com/pgjdbc/pgjdbc/compare/REL9.4.1208...REL42.3.3)
---
updated-dependencies:
- dependency-name: org.postgresql:postgresql
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Bump snakeyaml from 1.17 to 1.26 in /wayang-commons (#5)
Bumps [snakeyaml](https://bitbucket.org/asomov/snakeyaml) from 1.17 to 1.26.
- [Commits](https://bitbucket.org/asomov/snakeyaml/commits)
--- …

Update several dependencies

---

wayang-api/wayang-api-scala-java/src/main/scala/README.md
wayang-benchmark/src/main/scala/README.md
wayang-platforms/wayang-flink/src/main/scala/README.md
wayang-platforms/wayang-spark/src/main/scala/README.md
wayang-plugins/wayang-iejoin/src/main/scala/README.md
wayang-profiler/src/main/scala/README.md
wayang-tests-integration/src/main/scala/README.md

Several IDE load the project from the pom.xml file and activate the scala version recognization required to enable the scala profile, and the profile is automatically activated when the file `src/main/scala` [exist](https://github.com/apache/incubator-wayang/blob/1ca1e49822a8a65f6665d4616f8391ba12594234/pom.xml#L425-L431)

[WAYANG-IDE] add file to recognize the scala code in the IDE's

---

wayang-platforms/wayang-flink/code/main/java/org/apache/wayang/flink/compiler/KeySelectorDistinct.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkDistinctOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkJoinOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkReduceByOperatorTest.java

The implementation of KeySelectorDistinct was having a issue in the implementation.
In addition to this the test for the Join and ReduceBy in the flink platform were disable because of possible issue in the implementation.
Close #225

Correction in DistinctOperator for Apache Flink

---

.github/workflows/codeql.yml

https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

update to CodeQL v2

---

bin/wayang-submit
wayang-benchmark/README.md

Added more detailed instructions on how to run the benchmark programs and tweaked the wayang-submit script by wrapping arguments in quotes to avoid problems with spaces, parentheses, etc

Benchmarks detailed instructions

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangJoinVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlAPI.java

This PR makes extends the SQL API to also handle joins.
- Algebraic Joins are transpiled to Wayang Join Operator
- Since the JoinOperator outputs a Tuple2<Record, Record>, the join is fused with a MapOperator to output <Record>
- This is required to have downstream operations on joins such as projections/aggregations.
With this PR merged, Wayang can now support simple and basic SPJ queries for decoupled JDBC sources and CSV data sources.

SQL API extensions to support joins

---

pom.xml

as workaround also iCal4j - not sure if it works. I don't know why not using https://github.com/ical4j/ical4j which is BSD 3

add EPL and PD license

---

wayang-platforms/wayang-flink/code/main/java/org/apache/wayang/flink/operators/FlinkMaterializedGroupByOperator.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkMaterializedGroupByOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkSortOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkUnionAllOperatorTest.java

Note that the FlinkMaterializedGroupByOperatorTest, although it succeeds, it produces the following messages:
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/C:/Users/Mike/.m2/repository/com/esotericsoftware/kryo/kryo/2.24.0/kryo-2.24.0.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
[ERROR] WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.util.UnsafeUtil
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
These are also produced by its respective Spark test, …

Added the following flink operator tests: MaterializedGroupByOperator, SortOperator, UnionAllOperator

---

wayang-api/wayang-api-sql/pom.xml

After the calcite-core version was upgraded to 1.32.0, the cross-platform example was not running. We got the following error related to the calcite-linq4j dependency: 
Caused by: java.lang.NoSuchMethodException: org.apache.calcite.linq4j.EnumerableDefaults.repeatUnion(org.apache.calcite.linq4j.Enumerable,org.apache.calcite.linq4j.Enumerable,int,boolean,org.apache.calcite.linq4j.function.EqualityComparer,org.apache.calcite.linq4j.function.Function0)
at java.base/java.lang.Class.getMethod(Class.java:2321)
at org.apache.calcite.linq4j.tree.Types.lookupMethod(Types.java:309)
We tested on our fork and it works, when we upgraded the calcite-linq4j to 1.32.0 (in the wayang-api-sql pom file) as well, so the two dependency versions match.

update calcite-linq4j version in api-sql pom to match calcite-core version

---

wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkCoGroupOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkGlobalReduceOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkJoinOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkMapPartitionsOperatorTest.java
wayang-platforms/wayang-flink/code/test/java/org/apache/wayang/flink/operators/FlinkReduceByOperatorTest.java
wayang-platforms/wayang-flink/pom.xml
wayang-tests-integration/pom.xml

Support for Java 11 starts from Flink 1.10, whereas the project had Flink 1.7.1. See [here](https://nightlies.apache.org/flink/flink-docs-release-1.10/release-notes/flink-1.10.html#java-11-support-flink-10725).
I also, changed the Flink version on the wayang-tests-integration pom so as to have the same version throughout the project.

Updated Flink version and added some operator tests

---

wayang-platforms/wayang-java/src/main/java/org/apache/wayang/java/operators/JavaTextFileSource.java
wayang-platforms/wayang-java/src/test/java/org/apache/wayang/java/operators/JavaTextFileSourceTest.java
wayang-platforms/wayang-java/src/test/resources/banking-tx-small.csv

**JavaTextFileSource.java** provides a selection based on the file URL's protocol.
If **https** or **http** is used instead of file, we use an HTTPConnection Object to load the data.
The test class is **JavaTextFileSourceTest.java**.
The test runs on my system in the branch **rel/0.7.1**.

Modified the JavaTextFileSource so that a remote file can be loaded via HTTPS protocol (or HTTP)

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangAggregateVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rel/WayangAggregate.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rules/WayangRules.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java
wayang-api/wayang-api-sql/src/main/resources/model.json
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlAPI.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlTest.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java
wayang-api/wayang-api-sql/src/test/resources/model.json

- Creates a Logical Aggregate operator.
- Creates an Aggregate Operator that can handle simple SQL aggrgation queries.
- Precisely, the query can have 1 aggregation field, 0 or 1 grouping field, and SUM, MIN, MAX, COUNT, or AVG as the aggregate function.

SQL API: Add support for simple aggregation queries

---

wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/api/Configuration.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/api/Job.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/DefaultEstimatableCost.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/EstimatableCost.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/EstimatableCostFactory.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/enumeration/PlanImplementation.java

This PR proposes an abstraction of the current cost model.
As of now, the cost model uses a somewhat _hardcoded_ calculation. 
To make the optimizers cost calculation more pluggable and allow users to optimize for their desired cost metric, this PR provides an interface called _EstimatableCost_ that can be implemented to define custom ways of calculating costs. 
The current _hardcoded_ calculation was moved to _DefaultEstimatableCost_ and is used by default.
Example from `guides/WordCount.java`:
```java
public class CustomEstimatableCost implements EstimatableCost {
/* Provide concrete implementations to match desired cost function(s)
* by implementing the interface in this class.
*/
}
public class WordCount {
public static void main(String[] args) {
/* Create a Wayang context and specify …
```

Implement cost model abstraction to be pluggable

---

wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/api/WayangContext.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/ExplainTreeNode.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/ExplainUtils.java

References #417 
Users can define WayangPlans as usual, but instead of executing them, they can now use an explain command:
```java
// Debug into console
WayangContext.explain(wayangPlan, udfJars);
// Print to json files for later usage:
WayangContext.explain(wayangPlan, true, udfJars);
```
Example debug to console for WordCount:
```shell
== Wayang Plan ==
-+ [Alternative[[LocalCallbackSink[Collect result]]], Alternative[[JavaLocalCallbackSink[Collect result]]], Alternative[[SparkLocalCallbackSink[Collect result]]]]
-+ [Alternative[[ReduceBy[Add counters]]], Alternative[[JavaReduceBy[Add counters]]], Alternative[[SparkReduceBy[Add counters]]]]
-+ [Alternative[[Map[To lower case, add counter]]], Alternative[[JavaMap[To lower case, add counter]]], Alternative[[SparkMap[To lower case, add …
```

Add explain command to display debug information for inflated wayang plans and execution plans

---

wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/DataQuanta.scala
wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/PlanBuilder.scala

At this moment, the Scala API has no nice interface to use the new explain command.

Add explain utility to scala planBuilder

---

.gitignore
pom.xml
wayang-api/wayang-api-scala-java/pom.xml
wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/DataQuanta.scala
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/cardinality/CardinalityEstimatorManager.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/platform/CrossPlatformExecutor.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/ReflectionUtils.java
wayang-docs/pom.xml

When opening Wayang in my IDE it produced many errors, 
This PR fixes all of them (at least for my setup).
The main issue is that a default Java compile level is not set in the root POM.xml file, and therefore my IDE(vscode) does not know what to compile. While it is possible to add this as a configuration inside an individual's setup .vscode for Visual Code, I would still suggest moving it to a default setting. Because 1. the .vscode settings file is git ignored and 2. the IDE automatically picks up the default value set in the root parameters of the POM.xml.
The second issue i had was with wayang-api/wayang-api-scala-java/pom.xml. 
Unfortunately, my IDE did not compile correctly without adding a recursive dependency on its package:
```
<dependency>
<groupId>org.apache.wayang</groupId> …
```

Minor changes for compilation with raw mvn

---

guides/ml-in-Wayang.md

This PR provides a short .md-guide that shows an examplory usage of the previously introduced abstraction of the cost model.
The guide shows how it can be utilized in order to predict query plans runtimes with a pre-trained ML model.
Apache Wayang (incubating) can be customized with concrete
implementations of the `EstimatableCost` interface in order to optimize
for a desired metric.  The implementation can be enabled by providing it
to a `Configuration`.
```java
public class CustomEstimatableCost implements EstimatableCost {
/* Provide concrete implementations to match desired cost function(s)
* by implementing the interface in this class.
*/
}
public class WordCount {
public static void main(String[] args) {
/* Create a Wayang context and specify the platforms Wayang will consider */ …
```

Add first draft of ml-in-wayang.md

---

pom.xml

The version of the apache parent was aincient ... I updated it to a recent one.
Removed duplicate definition of the snapshot repos as the parent pom already contains there, but with a different if.

Tried to help getting the releases working again

---

wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/api/WayangContext.java

This proposes a functional interface to change the Loggers level with the `WayangContext`:
```java
context.setLogLevel(Level.ERROR);
```
The change provides better ergonomics and prevents having to fiddle with configuration files, when Context objects etc. can be created during plan building. Furthermore, this aligns with the API presented in other Apache projects like [Spark](https://github.com/apache/spark/blob/df5ef91f44bacf60b39bccecc049eb8cb5714b39/core/src/main/scala/org/apache/spark/SparkContext.scala#L398)

Set logLevel on WayangContext to allow doing it without conf file

---

wayang-applications/pom.xml

solves reproducible build issue found in 1.0.0 release:
https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/wayang/README.md

use m-jar-p version configured in parent

---

wayang-platforms/wayang-spark/src/main/java/org/apache/wayang/spark/operators/ml/SparkKMeansOperator.java

This PR fixes the implementation of fit() and transform() in SparkKMeansOperator.java, ensuring correctness in Apache Spark MLlib's KMeans clustering.
Changes
✅ Properly converts JavaRDD<double[]> to Dataset<Row> using convertToDataFrame().
✅ Uses the correct features and prediction column names.
✅ Ensures transform() outputs a Tuple2<double[], Integer> for better usability.
✅ Implements predict() method to return only the cluster labels.
Issue Fixed
🔧 Fixes Issue #364: "Support Fit and Transform in SparkKMeansOperator"
Testing
✔ Verified clustering correctness using sample RDD<double[]> input.
✔ Checked that cluster centers and predictions are accurately extracted.

[SPARK] Implement Correct fit() and transform() in SparkKMeansOperator

---

wayang-tests-integration/pom.xml

The verify step ran through locally.
The org.codehaus.janino dependency of spark needed to be set to a desired version.

Fix spark dependency version to fix integration tests

---

python/src/pywy/core/serializer.py
python/src/pywy/operators/binary.py
python/src/pywy/tests/join_test.py
python/src/pywy/tests/sandbox.py
wayang-api/wayang-api-python/src/main/java/org/apache/wayang/api/python/function/WrappedTransformationDescriptor.java

The python join operator's key extraction didn't work properly due to incorrect input handling. 
This resulted in a cartesian product, as both keys were null.

Fix join key extraction for python join operator

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangTableScanVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/optimizer/Optimizer.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/utils/ModelParser.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java
wayang-api/wayang-api-sql/src/test/resources/data/exampleInt.csv
wayang-api/wayang-api-sql/src/test/resources/data/exampleMin.csv
wayang-api/wayang-api-sql/src/test/resources/data/exampleRefToRef.csv
wayang-api/wayang-api-sql/src/test/resources/data/largeLeftTableIndex.csv
wayang-api/wayang-api-sql/src/test/resources/model-example-min.json

I've added a bunch of tests that tests common sql queries that aren't yet supported in the sql-api,
I've left them commented so it doesn't discourage people from pushing working commits yet. I'll have some implementations coming from my personal fork once I verify they are working on 1.0.

More testing for the sql-api & enable custom calcite models for TableScanVisitor

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangCrossJoinVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/FlattenJoinResult.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java
wayang-api/wayang-api-sql/src/test/resources/data/exampleSmallA.csv
wayang-api/wayang-api-sql/src/test/resources/data/exampleSmallB.csv

Added support & tests for cross joins / cartesian products in the sql-api, still missing an implementation for the ```JdbcExecutor```, so it just works for serialisation-based / java platforms.

add support for cross joins in the sql-api

---

wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/JavaPlanBuilder.scala
wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/PlanBuilder.scala
wayang-benchmark/src/main/java/org/apache/wayang/apps/wordcount/WordCountParquet.java
wayang-commons/wayang-basic/src/main/java/org/apache/wayang/basic/operators/ParquetSource.java
wayang-platforms/wayang-java/src/main/java/org/apache/wayang/java/mapping/ParquetSourceMapping.java
wayang-platforms/wayang-java/src/main/java/org/apache/wayang/java/operators/JavaParquetSource.java
wayang-platforms/wayang-spark/src/main/java/org/apache/wayang/spark/operators/SparkParquetSource.java

Users no longer need to provide the column names, they will be read by the operator itself.

Update Parquet operators to better use metadata early on

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangMultiConditionJoinVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/MultiConditionJoinFuncImpl.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/MultiConditionJoinKeyExtractor.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

Currently doesn't support JDBC, but works for java platforms

Multi conditional joins for sql-api

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangJoinVisitor.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

Due to the way we handle joins internally with the java key extractor i.e. over the input,
and how calcite handles joins i.e. a union type directly on the join. It was possible to get an out of bounds exception if you changed your sql join order from `tableA join tableB on tableA.col = tableB.col`  to `tableA join tableB on tableB.col = tableA.col`

fix a bug where tableA join tableB failed due to index sizes

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/ProjectMapFuncImpl.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

Since most functions used by the various `Visitor`s reference `RexNode` or `RexNode` sub-classes, they were unserialisable. I've moved all references to the `RexNode` into the constructor, this makes it serialisable and usable by platforms like Spark. Something similar should be done by other such functions.

Serialisability for sql-api projections

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangSortVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/SortFilter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rules/WayangSortRule.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

I had to divide the Calcite sort into a Wayang sort operator and a filter operator to capture the fetch offset limit info. Any comments on this are welcome.

fetch, offset & limit for java platforms in sql-api

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/ProjectMapFuncImpl.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

As `RexNode`s and inheritors of `RexNode` are not serializable by default in Calcite, and the serialisation utils are in their infancy. Similar approach should be used in the `FilterPredicateImpl`, https://github.com/apache/incubator-wayang/blob/main/wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/FilterPredicateImpl.java

fix serialization for RexCalls in sql-api projections

---

pom.xml
wayang-api/pom.xml
wayang-api/wayang-api-scala-java/pom.xml
wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/util/Parameters.scala
wayang-api/wayang-api-sql/pom.xml
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java
wayang-api/wayang-api-utils/pom.xml
wayang-api/wayang-api-utils/src/main/scala/Parameters.scala

Changes proposed in this PR allow named arguments for executable main function in `SqlContext.java`:
```shell
./bin/wayang-submit org.apache.wayang.api.sql.context.SqlContext -p java,spark,postgres -jdbcDriver org.postgresql.Driver -jdbcUrl jdbc:postgresql://job:5432/job -jdbcPassword postgres -o /var/www/html/data/benchmarks/ -d /var/www/html/data/ -q /var/www/html/data/test.sql -c file:///var/www/html/conf/wayang-defaults.properties -s file:///var/www/html/wayang-api/wayang-api-sql/src/main/resources/model.json
```

Use file based schema and named args for SqlContext main

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java

The main now correctly can use a configuration and won't discard the configuration when converting, furthermore it also adds the column names to the output.

Change main execution in sql-api

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/FilterPredicateImpl.java

If you had statements like column.id > 5, a class cast exception could happen if the column.id was of type long, while the literal 5 was of type int.

Fix class cast exception in sql-api where clauses

---

python/src/pywy/dataquanta.py
python/src/pywy/tests/test_train_linear_svc.py
wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/DataQuanta.scala
wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/DataQuantaBuilder.scala
wayang-commons/wayang-basic/src/main/java/org/apache/wayang/basic/model/SVMModel.java
wayang-commons/wayang-basic/src/main/java/org/apache/wayang/basic/operators/LinearSVCOperator.java
wayang-platforms/wayang-spark/src/main/java/org/apache/wayang/spark/mapping/Mappings.java
wayang-platforms/wayang-spark/src/main/java/org/apache/wayang/spark/mapping/ml/LinearSVCMapping.java
wayang-platforms/wayang-spark/src/main/java/org/apache/wayang/spark/operators/ml/SparkLinearSVCOperator.java
wayang-tests-integration/src/test/java/org/apache/wayang/tests/SparkIntegrationIT.java

This PR introduces a new LinearSVCOperator for training binary classification models using linear support vector machines (SVM) 
- LinearSVCOperator, SparkLinearSVCOperator, SVMModel interface
- LinearSVCMapping for Spark backend
- Integration test in SparkIntegrationIT.java
- .trainLinearSVC(...) added to DataQuanta and DataQuantaBuilder
- LinearSVC added in models.py
- .train_linear_svc(...) added to DataQuanta
- Test: test_train_linear_svc.py

Add LinearSVC Operator with Full API Support 

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java

This PR adds two rules to the SqlContexts main function, allowing to push down filters when possible. 
This avoids Cartesian products and produces the more expected Join with a condition.

Add Filter into join rule to avoid cartesian products

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangJoinVisitor.java

Calcite gives key indexes that correspond to the combining of both the left and right table, to get to the correct position in each, we have to subtract the field count of the left table from calcite's right key index. We use the fact that the smallest key always references the left table and can be eagerly used w/o offsets, and then calculate the right key with an offset.

Change join key index in sql api

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangFilterVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangJoinVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/AggregateFunction.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/CallTreeFactory.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/FilterPredicateImpl.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/ProjectMapFuncImpl.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

We are still missing some features to completely handle TPC-H
- Tree algebra for projections & joins
Sometimes you can have nested statements in joins e.g. if you have =($x, or($y,$z)), we need to be able to unpack this.
- Sub-queries
for now I have added sub-query remove rule from Calcite, however this doesn't handle all sub-query cases, especially if the sub-query is nested

Better support for TPCH-like queries

---

wayang-platforms/wayang-java/src/main/java/org/apache/wayang/java/operators/JavaTextFileSource.java
wayang-platforms/wayang-java/src/test/java/org/apache/wayang/java/operators/JavaTextFileSourceTest.java

I also switched to some of the newer file handling techniques, in my personal benchmarks I saw big gains on subsequent functions on the data, especially when parallelized.
Also re-enabled a test, and cleaned up in the old ones.

fix memory leak in java platform

---

pom.xml

Remove redundant overwrite to use Java17, (and congrats with the new release!)

Remove redundant overwrite to use Java17 in pom.xml
