apache/incubator-wayang

build.md
pom.xml
wayang-api/pom.xml
wayang-api/wayang-api-python/pom.xml
wayang-api/wayang-api-scala-java/pom.xml
wayang-commons/pom.xml
wayang-commons/wayang-basic/pom.xml
wayang-commons/wayang-core/pom.xml
wayang-distro/pom.xml
wayang-extensions/pom.xml
wayang-platforms/pom.xml
wayang-platforms/wayang-flink/pom.xml
wayang-platforms/wayang-giraph/pom.xml
wayang-platforms/wayang-graphchi/pom.xml
wayang-platforms/wayang-java/pom.xml
wayang-platforms/wayang-jdbc-template/pom.xml
wayang-platforms/wayang-postgres/pom.xml
wayang-platforms/wayang-spark/pom.xml
wayang-platforms/wayang-sqlite3/pom.xml
wayang-profiler/pom.xml
wayang-tests-integration/pom.xml

this commit are an update of the header license and adding the documentation of building

update license header and docs

---

build.md
pom.xml
src/main/script/prerequisiteCheck.groovy
wayang-api/pom.xml
wayang-api/wayang-api-python/pom.xml
wayang-api/wayang-api-scala-java/pom.xml
wayang-commons/pom.xml
wayang-commons/wayang-basic/pom.xml
wayang-commons/wayang-core/pom.xml
wayang-commons/wayang-core/src/test/java/org/apache/wayang/core/util/mathex/ExpressionBuilderTest.java
wayang-distro/pom.xml
wayang-extensions/pom.xml
wayang-extensions/wayang-iejoin/pom.xml
wayang-platforms/pom.xml
wayang-platforms/wayang-flink/pom.xml
wayang-platforms/wayang-giraph/pom.xml
wayang-platforms/wayang-graphchi/pom.xml
wayang-platforms/wayang-java/pom.xml
wayang-platforms/wayang-java/src/test/java/org/apache/wayang/java/operators/JavaObjectFileSinkTest.java
wayang-platforms/wayang-jdbc-template/pom.xml
wayang-platforms/wayang-postgres/pom.xml
wayang-platforms/wayang-spark/pom.xml
wayang-platforms/wayang-spark/src/test/java/org/apache/wayang/spark/operators/SparkObjectFileSinkTest.java
wayang-platforms/wayang-sqlite3/pom.xml
wayang-profiler/pom.xml
wayang-tests-integration/pom.xml

- Cleaned up the oder of entries in the pom.xmls
- Added a prerequisiteCheck.groovy to check all known conditions before starting the build and giving the user feedback on what he has to do.

- Made the antlr and scala profiles activate themselves on-demand

---

.travis.yml
build.md
pom.xml

This pull request add the coverage plugin called Jacoco to the maven. Also it's fix some issue with travis when some files doesn't exist.

[WAYANG-21] Coverage Test Plugin

---

.travis.yml
pom.xml
wayang-docs/pom.xml

Correct the missing element to the generation of the web documentation run with travis with any issues

Docs Corrections

---

wayang-commons/pom.xml
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/SimpleEstimationContext.java
wayang-commons/wayang-core/src/test/java/org/apache/wayang/core/optimizer/costs/NestableLoadProfileEstimatorTest.java
wayang-platforms/wayang-java/src/main/java/org/apache/wayang/java/operators/graph/JavaPageRankOperator.java
wayang-profiler/src/main/java/org/apache/wayang/profiler/log/GeneticOptimizer.java

It's important to focus on the TODO added because they may affect the performance of some code

[WAYANG-35] the library Trove4j was removed

---

.travis.yml
wayang-api/wayang-api-python/pom.xml
wayang-api/wayang-api-scala-java/pom.xml
wayang-commons/pom.xml
wayang-platforms/wayang-spark/pom.xml
wayang-platforms/wayang-spark/src/main/java/org/apache/wayang/spark/channels/RddChannel.java
wayang-platforms/wayang-spark/src/main/resources/wayang-spark-defaults.properties
wayang-platforms/wayang-spark/src/test/java/org/apache/wayang/spark/operators/SparkOperatorTestBase.java
wayang-plugins/wayang-iejoin/pom.xml
wayang-profiler/pom.xml
wayang-tests-integration/pom.xml

update Apache Spark version from 2.4.0 to 3.1.2 
the version of Apache Spark 3.1.2 it will be default version

[WAYANG-37] update Apache Spark version from 2.4.0 to 3.1.2

---

pom.xml
wayang-api/wayang-api-scala-java/pom.xml
wayang-commons/pom.xml
wayang-commons/wayang-core/pom.xml
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/monitor/FileMonitor.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/cardinality/CardinalityEstimate.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/EstimationContext.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/LoadEstimate.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/LoadProfile.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/LoadProfileEstimators.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/costs/SimpleEstimationContext.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/platform/AtomicExecution.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/platform/AtomicExecutionGroup.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/platform/PartialExecution.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/platform/Platform.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/profiling/CardinalityRepository.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/profiling/ExecutionLog.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/JsonSerializable.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/JsonSerializables.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/JsonSerializer.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/json/JSONArray.java
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/util/json/JSONObject.java
wayang-commons/wayang-core/src/test/java/org/apache/wayang/core/platform/PartialExecutionTest.java
wayang-commons/wayang-core/src/test/java/org/apache/wayang/core/test/SerializableDummyExecutionOperator.java
wayang-platforms/wayang-jdbc-template/src/main/java/org/apache/wayang/jdbc/operators/SqlToStreamOperator.java
wayang-platforms/wayang-spark/pom.xml
wayang-profiler/pom.xml
wayang-profiler/src/main/java/org/apache/wayang/profiler/log/DynamicLoadProfileEstimators.java
wayang-tests-integration/pom.xml

Apache Wayang was having some licenses issues, this got deleted following the step below:
- Add a License Checker (org.codehaus.mojo:license-maven-plugin:2.0.0) 
- The tool found the org.json have a not compatible license with Apache License
- The org.json was remove after a creation of a wrapper, the wrapper it not fully complete but it covering the requirements of the existing code

[WAYANG-38] Licences validation

---

.travis.yml
bin/build.sh
bin/change-scala-version.sh

- Travis build
- build.sh
- Deprecate the change-scala-version.sh script

[WAYANG-41] Fix some Scala version issues

---

wayang-plugins/wayang-hackit/wayang-hackit-sidecar/pom.xml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/java/org/apache/wayang/hackit/sidecar/HackitSidecar.java
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/java/org/apache/wayang/hackit/sidecar/test.java
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/java/org/apache/wayang/hackit/sidecar/webservice/ExecutorManager.java
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/java/org/apache/wayang/hackit/sidecar/webservice/WebService.java
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/application.properties
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/claim.yaml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/jobmanager-service.yaml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/jobmanager.yaml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/jobmanager_new.yaml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/loadbalancer.yaml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/taskmanager.yaml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/taskmanager_new.yaml
wayang-plugins/wayang-hackit/wayang-hackit-sidecar/src/main/resources/volume.yaml

Merging related changes about the debugger, It just to clean the branch that are not used for the future implementations

Debugger sidecar

---

pom.xml

upped version to 2.15 which has the critical issue fixed

CVE-2021-44228

---

NOTICE

Please remember to bring it when you next release ：）

Happy New Year, Update NOTICE year

---

.dlc.json
.github/workflows/dead-link-checker.yaml
wayang-benchmark/README.md
wayang-docs/src/main/resources/how_contribute/code_changes/preparing_contribute_code_changes/index.md
wayang-docs/src/main/resources/how_contribute/code_changes/preparing_contribute_code_changes/jira_issue.md
wayang-docs/src/main/resources/how_contribute/documentation_changes.md
wayang-docs/src/main/resources/how_contribute/reviewing_changes.md

He can help us detect dead links in MD documents when we submit PRs

[CI] Add deadlink check

---

.asf.yaml

Categorize PR notifications to the commits mailing list

Notification settings for repositories

---

.github/workflows/codeql.yml

https://github.com/github/codeql-action
It can help us to automatically check some security issues that may exist in the project

[CI]Add CodeQl Check

---

.asf.yaml

The activation of the Github Actions will allows to have better visibility of the project for the new people, but each will be replicate in Jira

Open the issues on Github

---

.github/workflows/ut.yml
.mvn/wrapper/maven-wrapper.properties
pom.xml

We have used the skywalking-eyes check license head, so we can remove RAT.

[CI]Add UT check 

---

.github/workflows/todo2issue.yml
.gitmodules
.licenserc.yaml
pom.xml
wayang-commons/wayang-core/src/main/java/org/apache/wayang/core/optimizer/SanityChecker.java

This incorporate the issue of repository [todo-to-issue-action](https://github.com/marketplace/actions/todo-to-issue) version [4.5.4](https://github.com/alstr/todo-to-issue-action/tree/v4.5.4) and the configuration to be execute as external repository

[CI] create Issues from the TODO in the code

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/dead-link-checker.yaml

The actions need to be executed just when the element are push or some pull request is targeting the main branch but not in all the branch

[CI] execute the method just in main branch

---

.asf.yaml
pom.xml

Set protected branches and review restrictions
ignore todo files license head check

[Github]Set protected branches and review restrictions

---

wayang-docs/pom.xml

https://github.com/apache/incubator-wayang/issues/80

fix #80 (code scanning alert)

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
pom.xml
wayang-commons/pom.xml
wayang-docs/src/main/resources/Gemfile.lock
wayang-platforms/wayang-postgres/pom.xml
wayang-platforms/wayang-spark/pom.xml

The protocol buffer is added in the generation of the environment for the compilation 
Solve #90

Protoc for the CI

---

wayang-platforms/wayang-spark/wayang-spark_2.11/pom.xml

This Pull request closes the issue #47 created in JIRA

[WAYANG-47] Properties Spark 2.11 updated with Spark version

---

.asf.yaml

the commit '7fc5b5489baa4cf78fa96c8d9f1f7b3b141ceb98' rollback old changes and need to delete until the correction are apply
This is for remote the commit that it producing the problems

Correction to delete commit

---

README.md

add r/ApacheWayang

---

wayang-benchmark/code/main/java/org/apache/wayang/apps/grep/Grep.java
wayang-benchmark/wayang-benchmark_2.11/pom.xml
wayang-benchmark/wayang-benchmark_2.12/pom.xml
wayang-platforms/wayang-flink/code/main/java/org/apache/wayang/flink/operators/FlinkTextFileSink.java
wayang-platforms/wayang-spark/code/main/resources/wayang-spark-defaults.properties

Inclusion of the benchmark Grep in the benchmark module and other minors

Add Grep Benchmark

---

.asf.yaml

Add a new label for better searching indexing

Add new label to repository

---

README.md

minor changes, travis link failed since travis is decommissioned

removed travis, added Apache Calcite support

---

README.md
bin/wayang-submit
tutorial.md

Added a link in README to the tutorial created by @bgeng777 and removed unnecessary printouts from the wayang-submit script

Updated instructions and wayang-submit

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangTableScanVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/schema/SchemaUtils.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlAPI.java
wayang-api/wayang-api-sql/src/test/resources/model.json

This PR mainly addresses issues #286 and consequently #305
- removes hardcoded calcite schemas
- removes hardcoded tablesource operators

SQL API dev

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangJoinVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangProjectVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangRelConverter.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangTableScanVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlAPI.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlTest.java

Michelle and I fixed a small bug on WayangJoinVisitor related to the UnsupportedOperationException which was not thrown before.
The rest of the contribution consists of documentation comments and minor clean ups.

Bugfix on WayangJoinVisitor

---

wayang-api/wayang-api-sql/pom.xml
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangTableScanVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/optimizer/Optimizer.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/rel/WayangTableScan.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlAPI.java
wayang-api/wayang-api-sql/src/test/resources/model.json

Add support for join across csv and postgres

Add cross-platform join

---

wayang-platforms/wayang-java/src/main/java/org/apache/wayang/java/plugin/JavaChannelConversionPlugin.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/plugin/SparkBasicPlugin.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/plugin/SparkGraphPlugin.java

Mainly corrected some comments I spotted were incorrect.

Errors correction

---

wayang-commons/wayang-basic/src/main/java/org/apache/wayang/basic/operators/KMeansOperator.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/Spark.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/mapping/Mappings.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/mapping/ml/KMeansMapping.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/operators/ml/SparkKMeansOperator.java
wayang-platforms/wayang-spark/code/main/java/org/apache/wayang/spark/plugin/SparkMLPlugin.java
wayang-platforms/wayang-spark/code/test/java/org/apache/wayang/spark/operators/SparkKMeansOperatorTest.java
wayang-platforms/wayang-spark/wayang-spark_2.11/pom.xml
wayang-platforms/wayang-spark/wayang-spark_2.12/pom.xml
wayang-tests-integration/code/test/java/org/apache/wayang/tests/SparkIntegrationIT.java

I implemented a naive kmeans operator on sparkml, and add two test cases. It is still in development. Maybe you can give me some advice on the code and design. Thanks!

naive kmeans operator on sparkml

---

guides/wayang-examples.md

This pull request introduces a Collaborative Filtering algorithm example to the Wayang Examples Guide.
Collaborative Filtering is a key technique used in Recommendation Systems. By including this example, we aim to provide users with a practical demonstration of how Wayang can be applied in this important area.
The example covers several steps including data loading, rating normalization, cosine similarity calculation between users, prediction of ratings for each user-item pair, and handling of cold start problems. This comprehensive approach gives users a clear understanding of how to implement such a system using Wayang.

Add Collaborative Filtering Example to Wayang Examples Guide

---

wayang-docs/src/main/resources/how_contribute/code_changes/preparing_contribute_code_changes/branching_strategy.md
wayang-docs/src/main/resources/how_contribute/code_changes/preparing_contribute_code_changes/index.md

#1 
Please have a review regarding the content.
Did I capture the proposed idea of the email thread correctly?
#2
Please review regarding docu fomat. 
I am not sure regarding the metadata in the head section of the page.
Just used it from a another docu page, but may be I missed a detail.

Summary of the email regarding branching strategy added as docu-extension

---

wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/JavaPlanBuilder.scala
wayang-api/wayang-api-scala-java/src/main/scala/org/apache/wayang/api/PlanBuilder.scala
wayang-platforms/wayang-java/src/main/java/org/apache/wayang/java/operators/JavaTextFileSource.java
wayang-platforms/wayang-spark/src/main/java/org/apache/wayang/spark/operators/SparkTextFileSource.java

- added changed files for new feature - read from textfile via URL

mk-feature-1 

---

NOTICE

Update profiledb details in NOTICE

---

README.md
RELEASE_NOTES
wayang-platforms/wayang-tensorflow/src/test/java/org/apache/wayang/tensorflow/model/TensorflowModelTest.java
wayang-tests-integration/src/test/java/org/apache/wayang/tests/TensorflowIntegrationIT.java

- Tensorflow tests are back (They run if he right java version is installed)
- updated README

some cleaning up

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/documentation.yml

changed actions/cache to v4

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangAggregateVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/AggregateAddCols.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/AggregateFunction.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/AggregateGetResult.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/AggregateKeyExtractor.java
wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java

I am not super happy with the design in ```AggregateFunction``` and how I / we handle types from records, if anyone has a recommendation / pattern feel free to comment.

better support for different types for aggregates in sql-api

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/context/SqlContext.java

Sqlcontext main should now correctly set calciteSchema on load

javadocs & inline loading

---

wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangAggregateVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangFilterVisitor.java
wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/functions/FilterPredicateImpl.java

rewrote the way we handle widening conversions, it should now be more comprehensive, also general code improvements.

PLUS & MINUS arithmetic for filters in sql-api
